### ISSUE TITLE
Website navbar and images don't look good on a phone

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/mindlogger-landing#4]

**Comment by timothycdykes** [comment]
I've made some changes that should suffice temporarily until something can be implemented for the navigation (like a hamburger menu). As for the images, I'm not sure of a good solution for that yet without splitting "images/mindlogger-montage-2484px.png" into separate images that are set to `display: none`, then `display: block` after the breakpoint at which point the original, larger image is then set to `display: none`.

**Comment by binarybottle** [comment]
I used a jekyll theme for https://matter.childmind.org/ that does a nice job of shrinking the navbar down to a hamburger menu.  mindlogger-landing should adopt something like this as well.

I was considering breaking up the montage into separate images, but would prefer that the whole image shrink rather than break up into a tall vertical column of images that would require the user to scroll down a ways on their phone.

**Comment by shnizzedy** [comment]
The previous version is still served at https://childmindinstitute.github.io/mindlogger-website/. I think it might be a better idea to transfer the content of this repo to that template than to continue tweaking this one.

**Comment by binarybottle** [comment]
Still working on mindlogger-landing for now -- navbar list is so short that we might not need a hamburger menu for now.  It looks good on my phone...
