### ISSUE TITLE
Small screens: Text overflowing elements on run.html and code.html

### ISSUE THREAD

**Issue by timothycdykes** [ChildMindInstitute/mindlogger-landing#6]
While checking for other responsive issues, I found that once the device width hits around 510px and less, some of the text overflows the parent element. This seems to only be happening with the content in the unordered list, specifically links as they are longer strings of text with no breaks.

![20191015_screenshot_mindlogger_01](https://user-images.githubusercontent.com/22033127/66880168-accd2c80-ef8f-11e9-8032-c0bb4015e83e.png)
![20191015_screenshot_mindlogger_02](https://user-images.githubusercontent.com/22033127/66880169-accd2c80-ef8f-11e9-90ab-994540ad44af.png)

**Comment by binarybottle** [comment]
I shortened all urls.  Looks better now...
